---
- hosts: webservers
  become: yes
  vars: 
    myvar1: shiva
    myvar2: shankar
  tasks:
  - name:  display myvar1
    debug:
      msg: "{{myvar1}}"

  - name: display myvar2
    debug:
      msg: "{{myvar2}}"